#!/usr/bin/env bash
#ddev-generated
## Description: Run Deployer (dep) inside the DDEV web container
## Usage:       dep [args]

if [ ! -f vendor/bin/dep ]; then
  echo 'deployer does not exist.'
  exit 1
fi

php vendor/bin/dep "$@"